// Package bootscript generates the on_boot.d script for UniFi Dream
// devices. A single script file at /data/on_boot.d/20-dddns.sh selects
// between the two run modes (cron, serve); `dddns config set-mode`
// writes the output of Generate into that path.
package bootscript

import "fmt"

// Params carries the paths embedded into the generated script. Callers
// typically pass DefaultUnifiParams; tests exercise alternative values.
type Params struct {
	Mode           string // "cron" or "serve"
	BinaryPath     string // e.g. /data/dddns/dddns
	ConfigDir      string // e.g. /data/.dddns
	CronEntryPath  string // e.g. /etc/cron.d/dddns
	UpdateLogPath  string // e.g. /var/log/dddns.log
	ServerLogPath  string // e.g. /var/log/dddns-server.log
	UpdateInterval string // crontab schedule; e.g. "*/30 * * * *"
}

// DefaultUnifiParams returns the production defaults for a UniFi install.
func DefaultUnifiParams(mode string) Params {
	return Params{
		Mode:           mode,
		BinaryPath:     "/data/dddns/dddns",
		ConfigDir:      "/data/.dddns",
		CronEntryPath:  "/etc/cron.d/dddns",
		UpdateLogPath:  "/var/log/dddns.log",
		ServerLogPath:  "/var/log/dddns-server.log",
		UpdateInterval: "*/30 * * * *",
	}
}

// Generate returns the full text of the on_boot.d script for the given
// parameters. The output is idempotent — running it repeatedly leaves
// the system in the same state.
func Generate(p Params) (string, error) {
	switch p.Mode {
	case "cron":
		return renderCron(p), nil
	case "serve":
		return renderServe(p), nil
	default:
		return "", fmt.Errorf("unknown mode %q (want cron or serve)", p.Mode)
	}
}

const commonHeader = `#!/bin/sh
# dddns boot script — generated by "dddns config set-mode".
# Do not edit by hand; re-run set-mode to change the mode.
set -eu

BINARY=%q
CONFIG_DIR=%q
CRON_PATH=%q

# Keep /usr/local/bin/dddns as a symlink to the /data-resident binary
# so it survives /usr rewrites across firmware upgrades.
if [ -f "$BINARY" ]; then
    ln -sf "$BINARY" /usr/local/bin/dddns
fi

# Create the config dir with owner-only perms if absent.
if [ ! -d "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
    chmod 700 "$CONFIG_DIR"
fi
`

const cronTail = `
# --- cron mode ---

# Stop any stray serve loop (guards switching from serve to cron).
pkill -f "dddns serve" >/dev/null 2>&1 || true

# Install / refresh the cron entry.
cat > "$CRON_PATH" <<'CRON'
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
%s root /usr/local/bin/dddns update --quiet >> %s 2>&1
CRON

/etc/init.d/cron restart >/dev/null 2>&1 || true
`

const serveTail = `
# --- serve mode ---

# Remove any stale cron entry (guards switching from cron to serve).
if [ -f "$CRON_PATH" ]; then
    rm -f "$CRON_PATH"
    /etc/init.d/cron restart >/dev/null 2>&1 || true
fi

# Stop any prior serve loop so re-running this script does not double-start.
pkill -f "dddns serve" >/dev/null 2>&1 || true

# Start the supervised listener. The subshell+while loop restarts dddns
# serve after a crash with a 5-second backoff; no external supervisor
# needed on UniFi OS.
(
    while true; do
        /usr/local/bin/dddns serve >> %s 2>&1
        sleep 5
    done
) &
`

func renderCron(p Params) string {
	return fmt.Sprintf(commonHeader, p.BinaryPath, p.ConfigDir, p.CronEntryPath) +
		fmt.Sprintf(cronTail, p.UpdateInterval, p.UpdateLogPath)
}

func renderServe(p Params) string {
	return fmt.Sprintf(commonHeader, p.BinaryPath, p.ConfigDir, p.CronEntryPath) +
		fmt.Sprintf(serveTail, p.ServerLogPath)
}
