// Package bootscript generates the on_boot.d script for UniFi Dream
// devices. A single script file at /data/on_boot.d/20-dddns.sh selects
// between the two run modes (cron, serve); `dddns config set-mode`
// writes the output of Generate into that path.
//
// Serve mode uses a systemd unit (standard on UniFi OS 2.x+) for
// supervision; cron mode installs an /etc/cron.d entry. Both artefacts
// live outside /data (they're on the wiped-by-firmware root FS), so
// the boot script re-installs them on every boot.
package bootscript

import "fmt"

// Params carries the paths embedded into the generated script. Callers
// typically pass DefaultUnifiParams; tests exercise alternative values.
type Params struct {
	Mode           string // "cron" or "serve"
	BinaryPath     string // e.g. /data/dddns/dddns
	ConfigDir      string // e.g. /data/.dddns
	CronEntryPath  string // e.g. /etc/cron.d/dddns
	UpdateLogPath  string // e.g. /var/log/dddns.log
	UpdateInterval string // crontab schedule; e.g. "*/30 * * * *"
}

// DefaultUnifiParams returns the production defaults for a UniFi install.
func DefaultUnifiParams(mode string) Params {
	return Params{
		Mode:           mode,
		BinaryPath:     "/data/dddns/dddns",
		ConfigDir:      "/data/.dddns",
		CronEntryPath:  "/etc/cron.d/dddns",
		UpdateLogPath:  "/var/log/dddns.log",
		UpdateInterval: "*/30 * * * *",
	}
}

// Generate returns the full text of the on_boot.d script for the given
// parameters. The output is idempotent — running it repeatedly leaves
// the system in the same state.
func Generate(p Params) (string, error) {
	switch p.Mode {
	case "cron":
		return renderCron(p), nil
	case "serve":
		return renderServe(p), nil
	default:
		return "", fmt.Errorf("unknown mode %q (want cron or serve)", p.Mode)
	}
}

const commonHeader = `#!/bin/sh
# dddns boot script — generated by "dddns config set-mode".
# Do not edit by hand; re-run set-mode to change the mode.
set -eu

BINARY=%q
CONFIG_DIR=%q
CRON_PATH=%q
SYSTEMD_UNIT=/etc/systemd/system/dddns.service

# Keep /usr/local/bin/dddns as a symlink to the /data-resident binary
# so it survives /usr rewrites across firmware upgrades.
if [ -f "$BINARY" ]; then
    ln -sf "$BINARY" /usr/local/bin/dddns
fi

# Create the config dir with owner-only perms if absent.
if [ ! -d "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
    chmod 700 "$CONFIG_DIR"
fi
`

const cronTail = `
# --- cron mode ---

# Stop + disable the serve systemd unit if present (guards switching
# from serve to cron). The unit file at /etc/systemd/system/ is the
# source of truth — removing it from /data/ alone would be undone on
# the next boot.
if [ -f "$SYSTEMD_UNIT" ]; then
    systemctl stop dddns.service >/dev/null 2>&1 || true
    systemctl disable dddns.service >/dev/null 2>&1 || true
    rm -f "$SYSTEMD_UNIT"
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

# Install / refresh the cron entry.
cat > "$CRON_PATH" <<'CRON'
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
%s root /usr/local/bin/dddns update --quiet >> %s 2>&1
CRON

/etc/init.d/cron restart >/dev/null 2>&1 || true
`

const serveTail = `
# --- serve mode ---

# Remove any stale cron entry (guards switching from cron to serve).
if [ -f "$CRON_PATH" ]; then
    rm -f "$CRON_PATH"
    /etc/init.d/cron restart >/dev/null 2>&1 || true
fi

# Install the systemd unit. /etc/systemd/system/ is wiped on firmware
# upgrade, which is also when this boot script re-runs — so the source
# of truth for the unit is this heredoc, not the installed file.
cat > "$SYSTEMD_UNIT" <<'UNIT'
[Unit]
Description=dddns serve-mode DNS updater
Documentation=https://github.com/descoped/dddns
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/dddns serve
Restart=always
RestartSec=5
# GOMEMLIMIT caps the Go heap (soft limit). dddns serve is idle most of the
# time; this keeps RSS bounded under sustained inadyn push load on
# memory-constrained routers (UDR7 / UDM family have modest RAM budgets).
Environment=GOMEMLIMIT=16MiB
StandardOutput=journal
StandardError=journal
SyslogIdentifier=dddns
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/data/.dddns /var/log

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable dddns.service >/dev/null 2>&1 || true
systemctl restart dddns.service
`

func renderCron(p Params) string {
	return fmt.Sprintf(commonHeader, p.BinaryPath, p.ConfigDir, p.CronEntryPath) +
		fmt.Sprintf(cronTail, p.UpdateInterval, p.UpdateLogPath)
}

func renderServe(p Params) string {
	return fmt.Sprintf(commonHeader, p.BinaryPath, p.ConfigDir, p.CronEntryPath) + serveTail
}
