# Test configuration for dddns
aws_profile: "test-profile"
aws_region: "eu-west-1"
hosted_zone_id: "Z1234567890ABC"
hostname: "test.example.com"
ttl: 600
ip_cache_file: "/tmp/test-dddns-cache.txt"
skip_proxy_check: true